credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: John Smith
      password: '$2b$12$u57IA1lGsBVEeRQlQgkE2eDUQsei5FfH/tmj1RfI18lDYXwF1vrEK' # Will be hashed automatically
      role: donor
    rbriggs:
      email: rbriggs@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Rebecca Briggs
      password: '$2b$12$eoj69AKxOpD3masKeYWA5uBHUrf3vbXtSZI4ohKQnbZ4q12Q1sbXi' # Will be hashed automatically
      role: receiver
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com

